In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [2]:
df = pd.read_csv("C:/Users/varun/OneDrive/Apps/Desktop/PROJECT/data/retail_sales_sql_cleaned.csv")

In [3]:
df.head()

,order_id,customer_id,customer_name,age,gender,region,city,product_category,product_name,quantity,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship,row_id,order_date
0,ORD-03903,CUST32603,Aarav Mehta,39,Other,Central,Raipur,Groceries,Sugar,8,346.32,0.00,4043.14,289.18,56.04,Debit Card,0,True,Returned,7,1,2024-08-15
1,ORD-02198,CUST07881,Sanjay Verma,28,Male,West,Mumbai,Beauty,Sunscreen,8,858.66,0.08,9147.31,5355.56,64.49,Debit Card,5,False,Delivered,2,2,2022-08-16
2,ORD-01348,CUST49296,Pooja Sharma,41,Other,West,Surat,Furniture,Sofa,4,25941.32,0.14,110156.97,36956.51,67.65,Debit Card,4,False,Delivered,5,3,2021-08-29
3,ORD-02076,CUST05587,Priya Reddy,29,Other,West,Ahmedabad,Furniture,Bed Frame,9,22071.92,0.17,262066.11,66644.99,54.47,EMI,3,False,Delivered,4,4,2022-07-05
4,ORD-00287,CUST58035,Ritu Sharma,9,Male,Central,Nagpur,Groceries,Cooking Oil,1,320.06,0.31,323.95,31.38,48.81,Net Banking,4,False,Pending,4,5,2020-05-07

In [4]:
df.tail()

,order_id,customer_id,customer_name,age,gender,region,city,product_category,product_name,quantity,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship,row_id,order_date
4064,ORD-03220,CUST05571,Vikram Mehta,44,Other,West,Ahmedabad,Books,Fiction Novel,6,1199.21,0.09,7876.86,3776.83,61.99,EMI,5,False,Shipped,3,4143,2023-10-24
4065,ORD-00476,CUST99185,Rahul Das,46,Female,West,Surat,Clothing,T-Shirt,7,359.64,0.12,2673.78,1271.43,58.05,Debit Card,3,False,Delivered,3,4144,2020-07-29
4066,ORD-01500,CUST23783,Meera Nair,0,Female,Central,Bhopal,Books,Comic Book,7,1014.70,0.07,5508.78,1716.12,31.99,Debit Card,2,False,Delivered,8,4145,2021-11-03
4067,ORD-00213,CUST16925,Rohan Sharma,33,Male,Central,Nagpur,Beauty,Lipstick,3,538.36,0.03,1938.58,978.30,42.00,UPI,1,False,Delivered,10,4146,2020-04-02
4068,ORD-03513,CUST75619,Rahul Joshi,45,Other,East,Guwahati,Electronics,Smartwatch,7,70949.08,0.21,539413.90,58300.98,79.98,Cash on Delivery,4,False,Shipped,4,4147,2024-03-08

In [5]:
df.sample(5)

,order_id,customer_id,customer_name,age,gender,region,city,product_category,product_name,quantity,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship,row_id,order_date
3086,ORD-01176,CUST37244,Aditya Bhat,32,Other,Central,Raipur,Clothing,Saree,7,2184.88,0.16,20358.67,4252.26,49.09,EMI,4,False,Delivered,5,3131,2021-06-10
2835,ORD-00932,CUST66017,Nisha Chatterjee,35,Male,South,Bangalore,Electronics,Smartphone,4,40123.00,0.30,106939.95,10117.28,58.87,Net Banking,0,True,Returned,10,2875,2021-02-25
1393,ORD-01123,CUST18686,Rahul Shah,36,Other,West,Ahmedabad,Furniture,Bookshelf,1,19884.83,0.21,23868.33,5629.58,50.84,Net Banking,2,False,Delivered,8,1407,2021-05-23
103,ORD-01993,CUST20457,Vikram Kumar,40,Other,North,Ludhiana,Sports,Tennis Racket,9,14422.23,0.21,145427.41,40739.98,58.92,EMI,5,False,Delivered,1,104,2022-05-30
1150,ORD-04018,CUST05715,Shreya Kumar,30,Other,North,Ludhiana,Furniture,Desk,3,20526.57,0.39,39110.30,5636.16,58.12,EMI,5,False,Delivered,5,1162,2024-10-06

In [6]:
print(df.shape)

(4069, 22)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4069 entries, 0 to 4068
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               4069 non-null   object
 1   customer_id            4069 non-null   object
 2   customer_name          4069 non-null   object
 3   age                    4069 non-null   int64
 4   gender                 4069 non-null   object
 5   region                 4069 non-null   object
 6   city                   4069 non-null   object
 7   product_category       4069 non-null   object
 8   product_name           4069 non-null   object
 9   quantity               4069 non-null   int64
 10  unit_price             4069 non-null   float64
 11  discount_pct           4069 non-null   float64
 12  sales_amount           4069 non-null   float64
 13  profit                 4069 non-null   float64
 14  shipping_cost          4069 non-null   float64
 15  payment_method         4069 non-null   object
 16  customer_satisfaction  4069 non-null   int64
 17  return_flag            4069 non-null   bool
 18  order_status           4069 non-null   object
 19  days_to_ship           4069 non-null   int64
 20  row_id                 4069 non-null   int64
 21  order_date             4069 non-null   object
dtypes: bool(1), float64(5), int64(5), object(11)
memory usage: 671.7+ KB

In [8]:
df.describe()

,age,quantity,unit_price,discount_pct,sales_amount,profit,shipping_cost,customer_satisfaction,days_to_ship,row_id
count,4069.000000,4069.000000,4069.000000,4069.000000,4.069000e+03,4.069000e+03,4069.000000,4069.000000,4069.000000,4069.000000
mean,34.365938,7.455640,10716.212177,0.195601,6.458136e+04,1.209544e+04,63.409644,2.775621,5.509953,2061.417547
std,36.477267,44.109854,17422.115954,0.121504,3.244614e+05,5.417244e+04,18.358988,1.586427,4.264165,1195.489681
min,-7.000000,1.000000,50.260000,0.000000,3.945000e+01,1.560000e+00,-4.290000,0.000000,0.000000,1.000000
25%,25.000000,3.000000,675.220000,0.090000,2.579450e+03,7.477500e+02,50.800000,1.000000,3.000000,1026.000000
50%,34.000000,5.000000,2232.870000,0.200000,9.976280e+03,3.313530e+03,63.480000,3.000000,5.000000,2058.000000
75%,42.000000,8.000000,12892.310000,0.300000,5.264879e+04,1.093310e+04,75.820000,4.000000,8.000000,3095.000000
max,999.000000,999.000000,79957.920000,0.400000,1.736031e+07,2.445648e+06,133.350000,5.000000,100.000000,4147.000000

In [9]:
df.describe(include="object")

,order_id,customer_id,customer_name,gender,region,city,product_category,product_name,payment_method,order_status,order_date
count,4069,4069,4069,4069,4069,4069,4069,4069,4069,4069,4069
unique,4069,3988,400,3,5,20,7,42,6,9,1578
top,ORD-03903,CUST00213,Priya Verma,Male,West,Surat,Clothing,Shampoo,UPI,Delivered,2023-01-12
freq,1,3,21,1371,845,228,615,112,726,2531,9

In [10]:
df.isnull().sum()

order_id                 0
customer_id              0
customer_name            0
age                      0
gender                   0
region                   0
city                     0
product_category         0
product_name             0
quantity                 0
unit_price               0
discount_pct             0
sales_amount             0
profit                   0
shipping_cost            0
payment_method           0
customer_satisfaction    0
return_flag              0
order_status             0
days_to_ship             0
row_id                   0
order_date               0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
for col in df.columns:
    print(col)
    print(df[col].nunique())
    print("-"*40)

order_id
4069
----------------------------------------
customer_id
3988
----------------------------------------
customer_name
400
----------------------------------------
age
80
----------------------------------------
gender
3
----------------------------------------
region
5
----------------------------------------
city
20
----------------------------------------
product_category
7
----------------------------------------
product_name
42
----------------------------------------
quantity
11
----------------------------------------
unit_price
4060
----------------------------------------
discount_pct
41
----------------------------------------
sales_amount
4068
----------------------------------------
profit
4050
----------------------------------------
shipping_cost
3074
----------------------------------------
payment_method
6
----------------------------------------
customer_satisfaction
6
----------------------------------------
return_flag
2
----------------------------------------
order_status
9
----------------------------------------
days_to_ship
13
----------------------------------------
row_id
4069
----------------------------------------
order_date
1578
----------------------------------------

In [14]:
df.memory_usage(deep=True)

Index                       132
order_id                 236002
customer_id              236002
customer_name            245321
age                       32552
gender                   219689
region                   219590
city                     227918
product_category         230878
product_name             231373
quantity                  32552
unit_price                32552
discount_pct              32552
sales_amount              32552
profit                    32552
shipping_cost             32552
payment_method           235738
customer_satisfaction     32552
return_flag                4069
order_status             234418
days_to_ship              32552
row_id                    32552
order_date               240071
dtype: int64

In [15]:
df.memory_usage(deep=True).sum()/1024**2

np.float64(2.7529916763305664)