# Load Dataset

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/varun/OneDrive/Apps/Desktop/PROJECT/01_data/retail_sales_sql_cleaned.csv")

df["order_date"] = pd.to_datetime(df["order_date"])

---------------------------------------------------------------------------------------------------------------------------------------------------
# Time Features

### Years:

In [ ]:
df["year"] = df["order_date"].dt.year

### Quarter:

In [ ]:
df["quarter"] = df["order_date"].dt.quarter

### Month:

In [ ]:
df["month"] = df["order_date"].dt.month

### MONTH NAME:

In [ ]:
df["month_name"] = df["order_date"].dt.month_name()

### Day Name:

In [ ]:
df["day_name"] = df["order_date"].dt.day_name()

### Week name:

In [ ]:
df["week"] = df["order_date"].dt.isocalendar().week

-----------------------------------------------------------------------------------------------------------------------------------------------------
# Profit Features

### Profit Margin %:

In [ ]:
df["profit_margin_pct"] = (
    df["profit"] / df["sales_amount"] * 100
).round(2)

### Profit Category:

In [ ]:
df["profit_category"] = np.where(
    df["profit"] > 0,
    "Profit",
    "Loss"
)

### Profit Band:

In [ ]:
df["profit_band"] = pd.cut(
    df["profit"],
    bins=[-10000,0,100,500,1000,100000],
    labels=[
        "Loss",
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

---------------------------------------------------------------------------------------------------------------------------------------------------
# Discount features

### Discount %:

In [ ]:
df["discount_percentage"] = (
    df["discount_pct"]*100
).round(0)

### Discount Band:

In [ ]:
df["discount_band"] = pd.cut(
    df["discount_pct"],
    bins=[0,.10,.20,.30,.40,1],
    labels=[
        "0-10%",
        "10-20%",
        "20-30%",
        "30-40%",
        "40%+"
    ],
    include_lowest=True
)

---------------------------------------------------------------------------------------------------------------------------------------------------
# Customer Features

### Customer Lifetime Sales:

In [ ]:
customer_sales = (
    df.groupby("customer_id")["sales_amount"]
      .transform("sum")
)

df["customer_lifetime_sales"] = customer_sales

### Customer Segment:

In [ ]:
df["customer_segment"] = pd.qcut(
    df["customer_lifetime_sales"],
    q=4,
    labels=[
        "Bronze",
        "Silver",
        "Gold",
        "Platinum"
    ]
)

### Customer Order Count:

In [ ]:
df["customer_orders"] = (
    df.groupby("customer_id")["order_id"]
      .transform("nunique")
)

---------------------------------------------------------------------------------------------------------------------------------------------------
# Shipping Features

### Shipping Performance:

In [ ]:
df["shipping_performance"] = np.where(
    df["days_to_ship"] <= 3,
    "Fast",
    "Slow"
)

---------------------------------------------------------------------------------------------------------------------------------------------------
# Sales features

### Average Selling Price:

In [ ]:
df["average_selling_price"] = (
    df["sales_amount"]/df["quantity"]
).round(2)

### High Value Order:

In [ ]:
df["high_value_order"] = np.where(
    df["sales_amount"]>=500,
    "Yes",
    "No"
)

### Order Size:

In [ ]:
df["order_size"] = pd.cut(
    df["sales_amount"],
    bins=[0,100,300,700,100000],
    labels=[
        "Small",
        "Medium",
        "Large",
        "Enterprise"
    ]
)

---------------------------------------------------------------------------------------------------------------------------------------------------
# Return features

### Returned Order:

In [ ]:
df["is_returned"] = np.where(
    df["return_flag"]==True,
    1,
    0
)

### Satisfaction level:

In [ ]:
df["satisfaction_level"] = pd.cut( 
    df["customer_satisfaction"],
    bins=[0,2,3,4,5], 
    labels=[ "Poor", "Average", "Good", "Excellent" ] )

---------------------------------------------------------------------------------------------------------------------------------------------------
# Final validation

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4069 entries, 0 to 4068
Data columns (total 42 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 4069 non-null   object
 1   customer_id              4069 non-null   object
 2   customer_name            4069 non-null   object
 3   age                      4069 non-null   int64
 4   gender                   4069 non-null   object
 5   region                   4069 non-null   object
 6   city                     4069 non-null   object
 7   product_category         4069 non-null   object
 8   product_name             4069 non-null   object
 9   quantity                 4069 non-null   int64
 10  unit_price               4069 non-null   float64
 11  discount_pct             4069 non-null   float64
 12  sales_amount             4069 non-null   float64
 13  profit                   4069 non-null   float64
 14  shipping_cost            4069 non-null   float64
 15  payment_method           4069 non-null   object
 16  customer_satisfaction    4069 non-null   int64
 17  return_flag              4069 non-null   bool
 18  order_status             4069 non-null   object
 19  days_to_ship             4069 non-null   int64
 20  row_id                   4069 non-null   int64
 21  order_date               4069 non-null   datetime64[ns]
 22  is_returned              4069 non-null   int64
 23  year                     4069 non-null   int32
 24  quarter                  4069 non-null   int32
 25  month                    4069 non-null   int32
 26  month_name               4069 non-null   object
 27  day_name                 4069 non-null   object
 28  week                     4069 non-null   UInt32
 29  discount_percentage      4069 non-null   float64
 30  discount_band            4069 non-null   category
 31  customer_lifetime_sales  4069 non-null   float64
 32  customer_segment         4069 non-null   category
 33  customer_orders          4069 non-null   int64
 34  shipping_performance     4069 non-null   object
 35  average_selling_price    4069 non-null   float64
 36  high_value_order         4069 non-null   object
 37  order_size               3389 non-null   category
 38  satisfaction_level       3735 non-null   category
 39  profit_margin_pct        4069 non-null   float64
 40  profit_category          4069 non-null   object
 41  profit_band              4037 non-null   category
dtypes: UInt32(1), bool(1), category(5), datetime64[ns](1), float64(9), int32(3), int64(7), object(15)
memory usage: 1.1+ MB

In [32]:
df.head()

,order_id,customer_id,customer_name,age,gender,region,city,product_category,product_name,quantity,...,customer_segment,customer_orders,shipping_performance,average_selling_price,high_value_order,order_size,satisfaction_level,profit_margin_pct,profit_category,profit_band
0,ORD-03903,CUST32603,Aarav Mehta,39,Other,Central,Raipur,Groceries,Sugar,8,...,Silver,1,Slow,505.39,Yes,Enterprise,NaN,7.15,Profit,Medium
1,ORD-02198,CUST07881,Sanjay Verma,28,Male,West,Mumbai,Beauty,Sunscreen,8,...,Silver,1,Fast,1143.41,Yes,Enterprise,Excellent,58.55,Profit,Very High
2,ORD-01348,CUST49296,Pooja Sharma,41,Other,West,Surat,Furniture,Sofa,4,...,Platinum,1,Slow,27539.24,Yes,NaN,Good,33.55,Profit,Very High
3,ORD-02076,CUST05587,Priya Reddy,29,Other,West,Ahmedabad,Furniture,Bed Frame,9,...,Platinum,1,Slow,29118.46,Yes,NaN,Average,25.43,Profit,Very High
4,ORD-00287,CUST58035,Ritu Sharma,9,Male,Central,Nagpur,Groceries,Cooking Oil,1,...,Bronze,1,Slow,323.95,No,Large,Good,9.69,Profit,Low

In [33]:
df.describe()

,age,quantity,unit_price,discount_pct,sales_amount,profit,shipping_cost,customer_satisfaction,days_to_ship,row_id,...,is_returned,year,quarter,month,week,discount_percentage,customer_lifetime_sales,customer_orders,average_selling_price,profit_margin_pct
count,4069.000000,4069.000000,4069.000000,4069.000000,4.069000e+03,4.069000e+03,4069.000000,4069.000000,4069.000000,4069.000000,...,4069.000000,4069.000000,4069.000000,4069.000000,4069.0,4069.000000,4.069000e+03,4069.000000,4069.000000,4069.000000
mean,34.365938,7.455640,10716.212177,0.195601,6.458136e+04,1.209544e+04,63.409644,2.775621,5.509953,2061.417547,...,0.144999,2022.003441,2.509216,6.518063,26.531334,19.560088,7.115648e+04,1.040305,10114.869491,27.025080
min,-7.000000,1.000000,50.260000,0.000000,3.945000e+01,1.560000e+00,-4.290000,0.000000,0.000000,1.000000,...,0.000000,2020.000000,1.000000,1.000000,1.0,0.000000,3.945000e+01,1.000000,28.200000,2.240000
25%,25.000000,3.000000,675.220000,0.090000,2.579450e+03,7.477500e+02,50.800000,1.000000,3.000000,1026.000000,...,0.000000,2021.000000,2.000000,4.000000,13.0,9.000000,2.702940e+03,1.000000,595.660000,13.100000
50%,34.000000,5.000000,2232.870000,0.200000,9.976280e+03,3.313530e+03,63.480000,3.000000,5.000000,2058.000000,...,0.000000,2022.000000,3.000000,7.000000,27.0,20.000000,1.053218e+04,1.000000,2004.620000,26.770000
75%,42.000000,8.000000,12892.310000,0.300000,5.264879e+04,1.093310e+04,75.820000,4.000000,8.000000,3095.000000,...,0.000000,2023.000000,3.000000,9.000000,39.0,30.000000,5.586482e+04,1.000000,11399.210000,37.850000
max,999.000000,999.000000,79957.920000,0.400000,1.736031e+07,2.445648e+06,133.350000,5.000000,100.000000,4147.000000,...,1.000000,2024.000000,4.000000,12.000000,53.0,40.000000,1.736751e+07,3.000000,126424.150000,70.950000
std,36.477267,44.109854,17422.115954,0.121504,3.244614e+05,5.417244e+04,18.358988,1.586427,4.264165,1195.489681,...,0.352143,1.394253,1.113176,3.434165,14.996404,12.150447,4.234791e+05,0.200411,17550.454565,14.310242

---------------------------------------------------------------------------------------------------------------------------------------------------
# Export Final Dataset

In [ ]:
df.to_csv(
    "C:/Users/varun/OneDrive/Apps/Desktop/PROJECT/01_data/retail_sales_final.csv",
    index=False
)